clean: true
author: 'Liam Nichols'
author_url: https://github.com/liamnichols
github_url: https://github.com/liamnichols/ListItemFormatter
github_file_prefix: https://github.com/liamnichols/ListItemFormatter/blob/master
xcodebuild_arguments: [-project, ListItemFormatter.xcodeproj, -scheme, 'ListItemFormatter iOS']
module: ListItemFormatter
module_version: 1.0
output: docs
theme: fullwidth
skip_undocumented: true
