lane :update_version do |options|

  version_number = options[:version_number] ||= UI.input "Please provide the version number:"
  tag = "v#{version_number}"

  UI.user_error! "Version #{version_number} already exists" if git_tag_exists(tag: tag)

  ensure_git_status_clean
  ensure_git_branch(branch: 'master')

  UI.message "Incrementing build number"
  Dir.chdir("..") do
    sh("agvtool", "next-version")
  end

  UI.message "Setting version number: #{version_number}"
  Dir.chdir("..") do
    sh("agvtool", "new-marketing-version", version_number)
  end

  UI.message "Updating Podspec"
  version_bump_podspec(path: "ListItemFormatter.podspec", version_number: version_number)

  git_commit(path: ".", message: "Update version to '#{version_number}'")
  add_git_tag(tag: tag)

  push_to_git_remote if UI.confirm "Push changes to remote?"
  create_release(version_number: version_number) if UI.confirm "Would you like to create the release for #{version_number}?"
end

lane :create_release do |options|

  version_number = options[:version_number] ||= UI.input "Please provide the version number:"
  tag = "v#{version_number}"
  name = options[:name] ||= "Please provide a name for this release:"

  carthage(command: "build", platform: "all", no_skip_current: true)
  carthage(command: "archive", output: "ListItemFormatter.framework.zip")

  set_github_release(repository_name: "liamnichols/ListItemFormatter", name: name, tag_name: tag, upload_assets: ["ListItemFormatter.framework.zip"])

  pod_push(use_bundle_exec: true)
end

lane :test do

  clear_derived_data

  run_tests(scheme: "ListItemFormatter iOS", device: "iPhone XS (12.1)", clean: true)
  run_tests(scheme: "ListItemFormatter iOS", device: "iPhone X (11.4)")
  run_tests(scheme: "ListItemFormatter iOS", device: "iPhone 7 (10.3.1)")
  run_tests(scheme: "ListItemFormatter iOS", device: "iPhone 6s (9.3)")

  run_tests(scheme: "ListItemFormatter tvOS", device: "Apple TV (12.1)", clean: true)

  run_tests(scheme: "ListItemFormatter macOS", destination: "platform=macOS", clean: true)

  carthage(command: "build", platform: "all", no_skip_current: true)
  pod_lib_lint
end

lane :import_data do |options|

  cldr_tag = options[:cldr_tag] ||= UI.input "Please specify the tag representing the CLDR data to import (https://github.com/unicode-cldr/cldr-json/tags):"

  UI.important "Importing CLDR data. Using tag #{cldr_tag}"
  next unless UI.confirm "Performing this task will overwrite the Source/Resources.xcassets directory. Are you sure you would like to continue?"

  import "import_cldr_data.rb"
  import_cldr_data(cldr_tag, "../Source/Resources.xcassets")

  UI.success "Complete!"
  run_tests(scheme: "ListItemFormatter macOS", destination: "platform=macOS", clean: true) if UI.confirm "Would you like to run macOS tests?"
end
